#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
needs bashrc
say "installing zoxide"
package_install zoxide
say "copying $HOME/.bashrc.d/zoxide.bashrc"
install_shell_config zoxide
attention "restart your session or source ~/.bashrc to apply changes"