#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs git
needs delta
needs gh

mkdir -p ~/.config/git/

read -p "Enter your git user name: " GIT_USER_NAME
read -p "Enter your git user email: " GIT_USER_EMAIL

cp ./config ~/.config/git/config
cp ./attributes ~/.config/git/attributes
cp ./ignore ~/.config/git/ignore

sed -i "s/EMAIL/$GIT_USER_EMAIL/g" ~/.config/git/config
sed -i "s/NAME/$GIT_USER_NAME/g" ~/.config/git/config
