#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "Installing code-server..."

version=$(get_github_release_version "coder/code-server")
say "Downloading code-server version $version"
apt_install_deb "https://github.com/coder/code-server/releases/download/v${version}/code-server_${version}_amd64.deb"

sudo systemctl enable --now code-server@$USER

say "Now visit http://127.0.0.1:8080. Your password is in ~/.config/code-server/config.yaml"
