#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
    needs bashrc

    if is_macos; then
      brew_install helmfile
    else
      url="https://github.com/helmfile/helmfile/releases/download/v${version}/helmfile_${version}_linux_amd64.tar.gz"

      pushtmp
      curl -sL "$url" | tar -xzv helmfile
      chmod +x helmfile
      sudo mv helmfile /usr/local/bin/
      popd
    fi

    say "copying $HOME/.bashrc.d/helmfile.bashrc"
    install_shell_config helmfile
    attention "restart your session or source ~/.bashrc to apply changes"
}

github_install_helper helmfile "helmfile/helmfile"
