#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

require_linux

say "Installing clipboard history manager"

curl_install_script http://install-clipboard.gustavosett.dev
sudo usermod -aG input $USER && newgrp input
