#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "Installing glow..."

if is_macos; then
  brew_install glow
  exit 0
fi

version=$(get_github_release_version "charmbracelet/glow")
say "Downloading glow version $version"
apt_install_deb "https://github.com/charmbracelet/glow/releases/download/v${version}/glow_${version}_amd64.deb"
