#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  if is_macos; then
    brew_install gh
    return 0
  fi

  apt_install_deb "https://github.com/cli/cli/releases/download/v${version}/gh_${version}_linux_amd64.deb"
}

github_install_helper gh "cli/cli"