#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs nerdfonts
needs bashrc

curl -sS https://starship.rs/install.sh | sh -s -- -f

say "copying $HOME/.bashrc.d/starship.bashrc"
install_shell_config starship
attention "restart your session or source ~/.bashrc to apply changes"
