#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "Installing opencode..."

if ! is_macos; then
  version=$(get_github_release_version "anomalyco/opencode")
  say "Downloading opencode version $version"
  apt_install_deb "https://github.com/anomalyco/opencode/releases/download/v${version}/opencode-desktop-linux-amd64.deb"
fi

curl_install_script https://opencode.ai/install
attention "restart your session or source ~/.bashrc to apply changes"
