#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "Installing fresh..."

pushtmp
curl -sL $(curl -s https://api.github.com/repos/sinelaw/fresh/releases/latest | grep "browser_download_url.*_$(dpkg --print-architecture)\.deb" | cut -d '"' -f 4) -o fresh-editor.deb && sudo dpkg -i fresh-editor.deb
popd
