#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  needs bashrc

  if is_macos; then
    url="https://github.com/alajmo/sake/releases/download/v${version}/sake_${version}_darwin_$(os_arch).tar.gz"
  else
    url="https://github.com/alajmo/sake/releases/download/v${version}/sake_${version}_linux_amd64.tar.gz"
  fi

  pushtmp
  wget "$url" -O "sake.tar.gz"
  tar -zxvf "sake.tar.gz"
  sudo install -m 755 sake /usr/local/bin/
  package_install mandoc
  man_install sake.1
  popd

  install_shell_config sake
}

github_install_helper sake alajmo/sake
