#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "installing broot"

needs wget
pushtmp

wget https://dystroy.org/broot/download/x86_64-linux/broot
chmod +x broot
sudo mv broot /usr/local/bin/broot

popd
