#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "installing arkade"
needs bashrc

curl -sLS https://get.arkade.dev | sudo sh

say "copying ~/.bashrc.d/arkade.bashrc"
cp arkade.bashrc ~/.bashrc.d/
attention "restart your session or source ~/.bashrc to apply changes"
