#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "installing arkade"
needs bashrc

if is_macos; then
  brew_install arkade
else
  curl_install_script https://get.arkade.dev
fi

say "copying ~/.bashrc.d/arkade.bashrc"
install_shell_config arkade
attention "restart your session or source ~/.bashrc to apply changes"
