#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|debian|ubuntu)  package_uninstall sshfs ;;
  fedora)              package_uninstall fuse-sshfs ;;
  macos)               brew_uninstall sshfs ;;
  *)                   warning "not available for distro:$DISTRO" ;;
esac
