#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp

  # Version can be found here: https://www.speedtest.net/apps/cli
  version=1.2.0

  if is_macos; then
    url="https://install.speedtest.net/app/cli/ookla-speedtest-${version}-macosx-universal.tgz"
  else
    url="https://install.speedtest.net/app/cli/ookla-speedtest-${version}-linux-x86_64.tgz"
  fi

  curl -L "$url" | tar xvz "speedtest"
  sudo install -m 755 speedtest /usr/local/bin/
  rm speedtest
  popd
}

general_install_helper speedtest
