#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "installing sdkman"

needs bashrc
curl_install_script https://get.sdkman.io

say "copying ~/.bashrc.d/sdkman.bashrc"
install_shell_config sdkman
attention "restart your session or source ~/.bashrc to apply changes"
