#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "Installing dev janitor..."

version=$(get_github_release_version "cocojojo5213/Dev-Janitor")

if is_macos; then
  if [[ "$(os_arch)" == "arm64" ]]; then
    asset="Dev.Janitor_${version}_aarch64.dmg"
  else
    asset="Dev.Janitor_${version}_x64.dmg"
  fi

  dmg_install_app "https://github.com/cocojojo5213/Dev-Janitor/releases/download/v${version}/${asset}" "Dev Janitor.app"
  exit 0
fi

apt_install_deb "https://github.com/cocojojo5213/Dev-Janitor/releases/download/v${version}/Dev.Janitor_${version}_amd64.deb"
