#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  if is_macos; then
    brew_install sampler
    return 0
  fi

  url="https://github.com/sqshq/sampler/releases/download/v${version}/sampler-${version}-linux-amd64"
  sudo wget "$url" -O /usr/local/bin/sampler
  sudo chmod +x /usr/local/bin/sampler
}

github_install_helper sampler sqshq/sampler
