#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs bashrc

case "$DISTRO" in
  macos)  brew_install bash-completion@2 ;;
  *)      if [[ "$DISTRO" == "arch" ]]; then
            package_install bash-completion
          fi ;;
esac

say "copying ~/.bashrc.d/bash_completion.bashrc"
install_shell_config bash_completion
attention "restart your session or source ~/.bashrc"
