#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "removing user bash completions"

if is_macos; then
  brew_uninstall bash-completion@2
fi

rm -f ~/.bash_completion
rm -rf ~/.bash_completion.d
remove_shell_config bash_completion
