#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "Installing gitwand..."

version=$(get_github_release_version "devlint/GitWand")

if is_macos; then
  dmg_install_app "https://github.com/devlint/GitWand/releases/download/v${version}/GitWand_${version}_universal.dmg" "GitWand.app"
  exit 0
fi

say "Downloading gitwand version $version"
apt_install_deb "https://github.com/devlint/GitWand/releases/download/v${version}/GitWand_${version}_amd64.deb"
