#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "installing k3d"
needs bashrc
curl_install_script https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
say "copying $HOME/.bashrc.d/k3d.bashrc"
install_shell_config k3d
attention "restart your session or source ~/.bashrc to apply changes"
