#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "Installing paseo..."

version=$(get_github_release_version "getpaseo/paseo")
say "Downloading paseo version $version"
apt_install_deb "https://github.com/getpaseo/paseo/releases/download/v${version}/Paseo-${version}-amd64.deb"
