#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
    apt_install_deb "https://github.com/dandavison/delta/releases/download/${version}/git-delta_${version}_amd64.deb"
}

github_install_helper delta "dandavison/delta"
