#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs pass

install_function() {
    if is_macos; then
      binary="docker-credential-pass-v${version}.darwin-$(os_arch)"
    else
      binary="docker-credential-pass-v${version}.linux-amd64"
    fi

    url="https://github.com/docker/docker-credential-helpers/releases/download/v${version}/${binary}"

    pushtmp
    wget "$url"
    chmod +x "$binary"
    sudo mv "$binary" /usr/local/bin/docker-credential-pass
    popd
}

github_install_helper docker-credential-pass "docker/docker-credential-helpers"
