#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  if is_macos; then
    brew_install pixi
    return 0
  fi

  url="https://github.com/prefix-dev/pixi/releases/download/v${version}/pixi-x86_64-unknown-linux-musl.tar.gz"

  pushtmp
  curl -sL "$url" | tar -xz pixi
  chmod +x pixi
  sudo mv pixi /usr/local/bin/
  popd
}

github_install_helper pixi "prefix-dev/pixi"
