#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  wget https://github.com/dalance/procs/releases/download/v${version}/procs-v${version}-x86_64-linux.zip
  unzip procs-v0.14.10-x86_64-linux.zip
  sudo install procs /usr/local/bin/procs
  rm -rf procs-*
  popd
}

github_install_helper procs "dalance/procs"
