#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "Installing druk..."

version=$(get_github_release_version "letstri/druk")
say "Downloading druk version $version"

if is_macos; then
  # druk ships no macos disk image, but its release contains a homebrew formula
  brew_install "https://raw.githubusercontent.com/letstri/druk/v${version}/druk.rb"
else
  apt_install_deb "https://github.com/letstri/druk/releases/download/v${version}/druk_${version}_amd64.deb"
fi