#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs bashrc

say "Installing uv"

curl_install_script https://astral.sh/uv/install.sh

say "Copy uv.bashrc"
install_shell_config uv
attention "restart your session or source ~/.bashrc to apply changes"