#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
case "$DISTRO" in
  arch)           package_uninstall fd ;;
  debian|ubuntu)  package_uninstall fd ;;
  fedora)         package_uninstall fd-find ;;
  macos)          brew_uninstall fd ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac
