#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs nerdfonts

install_function() {
    say "Installing lsd"

    if is_macos; then
      brew_install lsd
    else
      apt_install_deb "https://github.com/lsd-rs/lsd/releases/download/v${version}/lsd_${version}_amd64.deb"
    fi

    say "copying $HOME/.bashrc.d/lsd.bashrc"
    install_shell_config lsd
    attention "restart your session or source ~/.bashrc to apply changes"
}

github_install_helper lsd "lsd-rs/lsd"
